$(document).ready(function ($) {
    const allImages = [
        "Portfolio/Calantha",
  "Portfolio/Calantha/C (1).png",
  "Portfolio/Calantha/C (2).png",
  "Portfolio/Calantha/C (3).png",
  "Portfolio/Calantha/C (4).png",
  "Portfolio/Calantha/C (5).png",
  "Portfolio/Cloud",
  "Portfolio/Cloud/A.png",
  "Portfolio/Cloud/B.png",
  "Portfolio/Cloud/C.png",
  "Portfolio/Cloud/D.png",
  "Portfolio/Cloud/E.png",
  "Portfolio/Cloud/F.jpg",
  "Portfolio/Cloud/G.jpg",
  "Portfolio/Cloud/H.jpg",
  "Portfolio/Cloud/I.jpg",
  "Portfolio/Cloud/K.jpg",
  "Portfolio/Cloud/KK.jpg",
  "Portfolio/Cloud/Z.jpg",
  "Portfolio/GateWay",
  "Portfolio/GateWay/G (1).png",
  "Portfolio/GateWay/G (2).png",
  "Portfolio/GateWay/G (3).png",
  "Portfolio/GateWay/G (4).png",
  "Portfolio/GateWay/G (5).png",
  "Portfolio/GateWay/G (6).png",
  "Portfolio/GateWay/G (7).png",
  "Portfolio/Personal",
  "Portfolio/Personal/P (1).jpg",
  "Portfolio/Personal/P (2).jpg",
  "Portfolio/Personal/P (4).jpg",
  "Portfolio/Personal/P (4).png",
  "Portfolio/Personal/P (5).jpg",
  "Portfolio/Personal/P (5).png",
  "Portfolio/Personal/P (6).png",
  "Portfolio/Personal/P (7).jpg",
  "Portfolio/Personal/P (13).jpg",
  "Portfolio/Personal/P (31).png",
  "Portfolio/Slab",
  "Portfolio/Slab/S (1).png",
  "Portfolio/Slab/S (2).png",
  "Portfolio/Slab/S (3).png",
  "Portfolio/Slab/S (4).png",
  "Portfolio/Slab/S (5).png",
  "Portfolio/Slab/S (6).png",
  "Portfolio/Slab/S (7).png",
  "Portfolio/Slab/S (8).png",
  "Portfolio/Slab/S (9).png",
  "Portfolio/Slab/S (10).png",
  "Portfolio/Slab/S (11).png",
  "Portfolio/Slab/S (12).png",
  "Portfolio/Slab/S (13).png",
  "Portfolio/Zena",
  "Portfolio/Zena/Z (1).png",
  "Portfolio/Zena/Z (2).png",
  "Portfolio/Zena/Z (3).png",
  "Portfolio/Zena/Z (4).png",
  "Portfolio/Zena/Z (5).png",
  "Portfolio/Zena/Z (6).png",
  "Portfolio/Zena/Z (7).png",
  "Portfolio/Zena/Z (8).png",
  "Portfolio/Zena/Z (9).png",
  "Portfolio/Zena/Z (10).png",
  "Portfolio/Zena/Z (11).png",
  "Portfolio/Zena/Z (12).png",
  "Portfolio/Zena/Z (13).png",
  "Portfolio/Zena/Z (14).png",
  "Portfolio/Zena/Z (15).png",
  "Portfolio/Zena/Z (16).png",
  "Portfolio/Zena/Z (17).png",
  "Portfolio/Zena/Z (18).png",
  "Portfolio/Zena/Z (19).png",
  "Portfolio/Zena/Z (20).png",
  "Portfolio/Portfolio.jpg"
    ]

    // Generate image tags for each image
    const imageTags = allImages.map(image => `<img src="${image}" alt="${image} loading="lazy">`);
    // Get the reference to the current div
    var div = $('.imgHolder');
    imageTags.forEach(element => {
        div.append(element);
    });

});
